[package]
name = "pastebin"
version = "0.1.0"
edition = "2024"

[dependencies]
mime-sniffer = "0.1.3"
rand = "0.8"
rocket = "0.5.1"
rocket_prometheus = "0.10.1"
zip = { version = "8.1.0", features = ["aes-crypto", "zstd"] }
